### ISSUE TITLE
ImportError: cannot import name 'MutableSequence' from 'collections' (C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\collections\__init__.py)

### ISSUE THREAD

**Issue by MarkMurphy94** [ClayJarCom/HeightmapExport#16]
Not sure if this project is still being maintained, but I'm encountering this when trying to install the plugin on a windows machine.

ImportError: cannot import name 'MutableSequence' from 'collections' (C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\collections\__init__.py)

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\__init__.py", line 27, in classFactory
    from .heightmapexport import HeightmapExport
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\heightmapexport.py", line 20, in 
    from .heightmapexport_dialog import HeightmapExportDialog
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\heightmapexport_dialog.py", line 49, in 
    from .PathTracer import PathTracer,PathTracerGUI
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\PathTracer\__init__.py", line 1, in 
    from .main.path_tracer import PathTracer
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\PathTracer\main\path_tracer.py", line 16, in 
    from ..path import parse_path
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\PathTracer\path\__init__.py", line 1, in 
    from .path import Path, Line, Arc, CubicBezier, QuadraticBezier
  File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Mark/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HeightmapExport\PathTracer\path\path.py", line 3, in 
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\collections\__init__.py)
```

**Comment by GenericConfluent** [comment]
You're running Python 3.12. `MutableSequence` was moved to `collections.abc` in Python version 3.3, I believe, but it had aliases that allowed import from `collections` up until 3.10. You could try to run QGIS through Python 3.9 which may work. Otherwise, https://github.com/CBBosman/HeightmapExport may provide a working instance of the plugin since it was modified just 2 weeks from the time of posting. 

I think it's fair to conclude the project is no longer being maintained after 5 years of inactivity. Personally, though I think the better approach to export as a heightmap is to find the path of your raster layer under Properties > Source (export it as GeoTIFF first if it's not already in that format). Then convert it to a heightmap using the following command: https://gis.stackexchange.com/a/206786.

**Comment by VfxTDwiki** [comment]
Open the file 
C:\Users\xxx\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HeightmapExport\PathTracer\path\path.py
replace 
`from collections import MutableSequence`

by 
`from collections.abc import MutableSequence`

**Comment by VfxTDwiki** [comment]
> Otherwise, https://github.com/CBBosman/HeightmapExport may provide a working instance of the plugin since it was modified just 2 weeks from the time of posting.

Looks like It's working. Thanks for the info! 

If you want to update the files of the plugin C:\Users\xxx\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HeightmapExport
- don't delete all files of the original folder, 
- just replace the files of the plugin by the content of the repo

It missing one warning in the file C:\Users\xxx\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HeightmapExport\PathTracer\path\parser.py

For the line 
`FLOAT_RE = re.compile("[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?")`

Add a **r** after re.compile(
 `FLOAT_RE = re.compile(r"[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?")`
